//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManager.PresentationLayer
{


    public partial class DatabaseSettings
    {
        protected global::Telerik.Web.UI.RadTextBox tbxDataSource;

        protected global::Telerik.Web.UI.RadTextBox tbxInitialCatalog;

        protected global::Telerik.Web.UI.RadTextBox tbxUserId;

        protected global::Telerik.Web.UI.RadTextBox tbxPassword;

        protected global::Telerik.Web.UI.RadTextBox tbxBackupPath;

        protected global::System.Web.UI.WebControls.Label lblValidationText;

        protected global::System.Web.UI.WebControls.Button btnUpdate;

        protected global::System.Web.UI.WebControls.Button btnCancel;

        protected global::Telerik.Web.UI.RadWindowManager RadWindowManager1;
        
        protected global::Telerik.Web.UI.RadWindow RadWindow1;
    }
}
