//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManager.PresentationLayer
{
    public partial class Default
    {
        protected global::Telerik.Web.UI.RadTextBox tbxLogin;

        protected global::Telerik.Web.UI.RadTextBox tbxPassword;

        protected global::System.Web.UI.WebControls.Panel pnlValidation;

        protected global::System.Web.UI.WebControls.Label lblValidationText;

        protected global::Telerik.Web.UI.RadButton btnLogOn;

        protected global::System.Web.UI.WebControls.Panel pnlRunTheLoginWindow;       
    }
}
