//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManager.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StudentsManagerEntities : DbContext
    {
        public StudentsManagerEntities()
            : base("name=StudentsManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCommonSetting> tblCommonSettings { get; set; }
        public virtual DbSet<tblDictionary> tblDictionaries { get; set; }
        public virtual DbSet<tblDictionaryType> tblDictionaryTypes { get; set; }
        public virtual DbSet<tblEducationLevel> tblEducationLevels { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblEvent> tblEvents { get; set; }
        public virtual DbSet<tblEvent2EductionLevel> tblEvent2EductionLevel { get; set; }
        public virtual DbSet<tblGroup> tblGroups { get; set; }
        public virtual DbSet<tblPriceGroup> tblPriceGroups { get; set; }
        public virtual DbSet<tblStudent> tblStudents { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<vwDictionary4List> vwDictionary4List { get; set; }
        public virtual DbSet<vwEducationLevel4List> vwEducationLevel4List { get; set; }
        public virtual DbSet<vwEmployee4List> vwEmployee4List { get; set; }
        public virtual DbSet<vwStudent4List> vwStudent4List { get; set; }
        public virtual DbSet<vwUser4List> vwUser4List { get; set; }
        public virtual DbSet<vwGroup4List> vwGroup4List { get; set; }
    
        public virtual int prcMakeBackup(string pathOnly)
        {
            var pathOnlyParameter = pathOnly != null ?
                new ObjectParameter("pathOnly", pathOnly) :
                new ObjectParameter("pathOnly", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcMakeBackup", pathOnlyParameter);
        }
    }
}
