//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent2EductionLevel
    {
        public System.Guid Event { get; set; }
        public System.Guid StartEducationLevel { get; set; }
        public System.Guid EndEducationLevel { get; set; }
    
        public virtual tblEducationLevel tblEducationLevel { get; set; }
        public virtual tblEducationLevel tblEducationLevel1 { get; set; }
        public virtual tblEvent tblEvent { get; set; }
    }
}
