//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroup
    {
        public tblGroup()
        {
            this.tblStudents = new HashSet<tblStudent>();
            this.tblStudents1 = new HashSet<tblStudent>();
            this.tblStudents2 = new HashSet<tblStudent>();
            this.tblEmployees = new HashSet<tblEmployee>();
            this.tblEvents = new HashSet<tblEvent>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CurrentEducationLevel { get; set; }
        public Nullable<System.Guid> PrimaryInstructor { get; set; }
        public Nullable<System.Guid> SecondaryInstructor { get; set; }
    
        public virtual tblEducationLevel tblEducationLevel { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblEmployee tblEmployee1 { get; set; }
        public virtual ICollection<tblStudent> tblStudents { get; set; }
        public virtual ICollection<tblStudent> tblStudents1 { get; set; }
        public virtual ICollection<tblStudent> tblStudents2 { get; set; }
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
        public virtual ICollection<tblEvent> tblEvents { get; set; }
    }
}
