//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPriceGroup
    {
        public tblPriceGroup()
        {
            this.tblStudents = new HashSet<tblStudent>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte Position { get; set; }
        public int IndexInPercents { get; set; }
    
        public virtual ICollection<tblStudent> tblStudents { get; set; }
    }
}
