//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEducationLevel4List
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte Position { get; set; }
        public Nullable<int> MinScore { get; set; }
        public int MaxScore { get; set; }
        public System.Guid LanguageId { get; set; }
        public string LanguageName { get; set; }
    }
}
