//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee4List
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronomic { get; set; }
        public string SurnameAndInitails { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.Guid EmployeeTypeId { get; set; }
        public string EmployeeTypeName { get; set; }
    }
}
