//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStudent4List
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronomic { get; set; }
        public string SurnameAndInitials { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CurrentScore1 { get; set; }
        public Nullable<int> FirstTestScore1 { get; set; }
        public Nullable<int> CurrentScore2 { get; set; }
        public Nullable<int> FirstTestScore2 { get; set; }
        public Nullable<int> CurrentScore3 { get; set; }
        public Nullable<int> FirstTestScore3 { get; set; }
        public System.Guid PriceGroupId { get; set; }
        public string PriceGroupName { get; set; }
        public System.Guid Language1Id { get; set; }
        public string Language1Name { get; set; }
        public System.Guid Language2Id { get; set; }
        public string Language2Name { get; set; }
        public System.Guid Language3Id { get; set; }
        public string Language3Name { get; set; }
        public System.Guid Group1Id { get; set; }
        public string Group1Name { get; set; }
        public System.Guid Group2Id { get; set; }
        public string Group2Name { get; set; }
        public System.Guid Group3Id { get; set; }
        public string Group3Name { get; set; }
    }
}
