//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUser4List
    {
        public System.Guid Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string SurnameAndInitials { get; set; }
        public string EMail { get; set; }
        public string Phone { get; set; }
        public System.Guid UserTypeId { get; set; }
        public string UserTypeName { get; set; }
    }
}
